name: Test EPG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - run: python sync_epg.py

    - uses: actions/upload-artifact@v4
      with:
        name: epg
        path: epg.xml
